### ISSUE TITLE
Convert to function components & React Hooks

### ISSUE THREAD

**Issue by thadk** [codeforboston/windfall-elimination#135]
The code organization would be a lot clearer if we used [function components](https://reactjs.org/docs/components-and-props.html) and [React Hooks](https://reactjs.org/docs/hooks-intro.html) instead of class components.

We now have `useUserState` and `useUserStateActions` hooks to access the state of the app and manipulate it, respectively.

Converted [`src/pages/*`](https://github.com/codeforboston/windfall-elimination/tree/develop/src/pages) to function components?:
- [x] 404.tsx
- [x] About.tsx
- [x] faq.tsx  
- [x] index.tsx
- [x] prescreen-1a.tsx (Background / birthdate entry screen) #294 
- [x] prescreen-1b.tsx (Earnings screen) Thanks @sashamaryl #294 
- [x] prescreen-1c.tsx (Employment Status /windfall elimination question & pension specificiation) #294 
- [x] prescreen-1d.tsc (future earnings) - thanks @dylanesque  #251 
- [ ] print.tsx
- [ ] screen-2.tsx (results with both calculators)
- [x] screen-2a.tsx (Example walkthrough of calculations) - thanks @linesbetween #141 

Other major components:
- [ ] [`src/components/file-upload.tsx`](https://github.com/codeforboston/windfall-elimination/blob/develop/src/components/file-upload.tsx) (can be separated into individual components)

Feel free to create new component files as you go.

**Comment by thadk** [comment]
@olena-ageyeva do you want to help with this in early 2020? We are going to try to release everything on Jan 17, so ideally we'd have this sorted out a week and a half before.

**Comment by olena-ageyeva** [comment]
@thadk  Sure. I'd be delighted to. You'd like it to be completed by January 6-7sh, right? It looks like a lot of refactoring work in a short time, but I agree it will significantly simplify the code and it does make sense to do so before the release.  Will start working on it now.

**Comment by thadk** [comment]
Wow, great, whatever you think you can contribute will help.

I just added you to the project, maybe we can work on a (feel free to create) `reactHooks` branch on the main repository instead of using the forked branch git model so we can collaborate more directly.

An early version to show everyone the concept on Tue Jan 7 when we meet next would be excellent–I'm sure folks will need a bit of introduction to the new way of managing variables, etc.

**Comment by thadk** [comment]
New way to manage state is proposed in #142 which can be function component and/or hooks-compatible.

**Comment by thadk** [comment]
If you want to work on this for one of the other files: `src/pages/prescreen-1d.tsx` look at the two commits here: https://github.com/codeforboston/windfall-elimination/pull/251/files <sub>(it is currently skipped as has unfinished features: to see this file running for now you need to either go directly to the URL: e.g. https://ssacalculator.org/prescreen-1d/ or enable with the feature toggle `GATSBY_SHOW_FUTURE_EARNINGS_PAGE=true npm start`)</sub>

Reading this code around the `useUserStateActions` and `useUserState` might help too: https://github.com/codeforboston/windfall-elimination/blob/develop/src/pages/screen-2a.tsx

**Comment by thadk** [comment]
cc: @olena-ageyeva @linesbetween I updated this issue if you'd like to help on it. We also have the example as in the last comment.

**Comment by thadk** [comment]
Related PR: https://github.com/codeforboston/windfall-elimination/pull/294
